DOMAIN = "calendar_event_manager"
PANEL_URL = "calendar-event-manager"
PANEL_TITLE = "Calendar Event Manager"
PANEL_ICON = "mdi:calendar-edit"
PANEL_MODULE_URL = "/calendar_event_manager/calendar-event-manager-panel.js?v=1.0.0"

SERVICE_PREVIEW = "preview"
SERVICE_DELETE = "delete"
SERVICE_DELETE_MATCHING = "delete_matching"
SERVICE_REPLACE = "replace"
SERVICE_ADOPT = "adopt"
SERVICE_DELETE_SERIES = "delete_series"

CONF_ENTITY_ID = "entity_id"
CONF_UID = "uid"
CONF_RECURRENCE_ID = "recurrence_id"
CONF_RECURRENCE_RANGE = "recurrence_range"
CONF_START = "start"
CONF_END = "end"
CONF_SUMMARY = "summary"
CONF_DESCRIPTION = "description"
CONF_LOCATION = "location"
CONF_MATCH = "match"
CONF_DRY_RUN = "dry_run"
CONF_CONFIRMATION = "confirmation"
CONF_INCLUDE_RECURRING = "include_recurring"

MATCH_EXACT = "exact"
MATCH_CONTAINS = "contains"

CONFIRM_DELETE = "DELETE EVENT"
CONFIRM_DELETE_MATCHING = "DELETE MATCHING"
CONFIRM_REPLACE = "REPLACE EVENT"
CONFIRM_ADOPT = "ADOPT EVENT"
CONFIRM_DELETE_SERIES = "DELETE SERIES"
